# =====================
# Builder
# =====================
FROM rust:bookworm AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y \
    clang \
    lld \
    binutils \
 && rm -rf /var/lib/apt/lists/*

COPY . .
ENV SQLX_OFFLINE=true

RUN cargo build --release
RUN strip target/release/zero2prod


# =====================
# Runtime
# =====================
FROM debian:bookworm-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
    ca-certificates \
    openssl \
 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/zero2prod /app/zero2prod
COPY configuration /app/configuration

ENV APP_ENVIRONMENT=production
ENTRYPOINT ["/app/zero2prod"]
